/*
* The program shows how to many logs can fit
*   on a truck given the length of the logs.
*
* @author  Curtis Edwards
* @version 1.0
* @since   2024-02-19
*/

/**
* This is the standard "Hello, World!" program.
*/
final class LogTruckProgram  {

    /**
    * Prevent instantiation.
    * Throw an exception IllegalStateException.
    * if this is ever called
    *
    * @throws IllegalStateException if this is ever called
    *
    */
    private LogTruckProgram () {
        throw new IllegalStateException("Cannot be instantiated");
    }

    /**
    * The starting main() function.
    *
    * @param args No args will be used
    */
    public static void main(final String[] args) {
        /** 
        * This method of getting user input was generated by ChatGPT
        */

        // Create a Scanner object to read user input
        Scanner scanner = new Scanner(System.in);

        System.out.print("What length do you want your logs to be? (0.25, 0.5, 1): ");
        double logLength = scanner.nextDouble();

        double numberOfLogs = 1100 / (20 * logLength);

        System.out.println("The truck can carry " + numberOfLogs + " logs if they are " + logLength + "m long.");
        System.out.println("\nDone.");

        scanner.close();

    }
}
